server:
  port: 8080

  # database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    ?? PC? ????? Database??? ?? ???.
    url: jdbc:mysql://localhost:3306/delidutch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql? ??? ??? ?? ??? ?? ???.
    username: root
    password: rntqkdlfjtm1
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create